apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-nginx-app  # **Ensure this field is present and correctly set**
  annotations:
  argocd-image-updater.argoproj.io/image-kustomize: my-nginx-app=jakehazex21/my-nginx-app
  argocd-image-updater.argoproj.io/write-back-method: git
  argocd-image-updater.argoproj.io/write-back-target: branch:main
  argocd-image-updater.argoproj.io/my-nginx-app.update-strategy: alphabetical
  kubectl.kubernetes.io/last-applied-configuration: |
    {"apiVersion":"argoproj.io/v1alpha1","kind":"Application","metadata":{"annotations":{"argocd-image-updater.argoproj.io/image-kustomize":"my-nginx-app=jakehazex21/my-nginx-app","argocd-image-updater.argoproj.io/my-nginx-app.update-strategy":"alphabetical","argocd-image-updater.argoproj.io/write-back-method":"git","argocd-image-updater.argoproj.io/write-back-target":"branch:main"},"name":"my-nginx-app","namespace":"argocd"},"spec":{"destination":{"namespace":"default","server":"https://kubernetes.default.svc"},"project":"default","source":{"kustomize":{},"path":".","repoURL":"https://github.com/catinahat85/CloudFiLive.git","targetRevision":"main"},"syncPolicy":{"automated":{"prune":true,"selfHeal":true}}}}
spec:
  project: default
  source:
    repoURL: 'https://github.com/catinahat85/CloudFiLive.git'
    targetRevision: 'argo'
    path: '.'  # **Ensure this path correctly points to your kustomization.yaml**
    kustomize: {}
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: 'default'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
